---
- name: get updated keys
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  become: yes

# - name: Update all packages to their latest version
#   apt:
#     name: "*"
#     state: latest
#     allow_unauthenticated: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_installed_apps }}"
